### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jackoliveira** [Mikonos-App/site-mikonos#1]
- [ ] Definir biblioteca de estilos.
- [ ] Definir a UI do projeto.
- [ ] Fazer CRUD das entidades.
- [ ] Escrita de testes unitários.
- [ ] Fazer documentação.
- [ ] Subir para a produção.
